/*
* AUTO-GENERATED Proxy.js
* Generated by scripts/generate-proxy.js
* DO NOT EDIT THIS FILE DIRECTLY — edit subdomains.json, your app folders, or script/generate-proxy.js instead.
*/

import { NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";

export const PLATFORM_ROUTES = [
  {
    "subdomain": "admin",
    "externalRoutes": [
      "about-us",
      "contact-us",
      "login",
      "register"
    ],
    "internalRoutes": [
      "assignments",
      "dashboard",
      "documents",
      "events",
      "meetings",
      "messages",
      "reports"
    ]
  },
  {
    "subdomain": "careers",
    "externalRoutes": [
      "about-us",
      "contact-us",
      "login",
      "register"
    ],
    "internalRoutes": [
      "assignments",
      "dashboard",
      "documents",
      "events",
      "meetings",
      "messages",
      "reports"
    ]
  },
  {
    "subdomain": "parents",
    "externalRoutes": [
      "about-us",
      "contact-us",
      "login",
      "pricing",
      "register"
    ],
    "internalRoutes": [
      "assignments",
      "dashboard",
      "documents",
      "events",
      "family",
      "meetings",
      "messages",
      "reports"
    ]
  },
  {
    "subdomain": "teachers",
    "externalRoutes": [
      "about-us",
      "contact-us",
      "login",
      "register"
    ],
    "internalRoutes": [
      "assignments",
      "dashboard",
      "documents",
      "events",
      "meetings",
      "messages",
      "reports"
    ]
  }
];

export const ROOT_EXTERNAL_ROUTES = [
  "about-us",
  "contact-us",
  "login",
  "pricing",
  "register"
];
export const ROOT_INTERNAL_ROUTES = [
  "assignments",
  "dashboard",
  "documents",
  "events",
  "meetings",
  "messages",
  "reports"
];

export const config = {
matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
};

function findPlatformRoutesForSubdomain(subdomain) {
return PLATFORM_ROUTES.find((p) => p.subdomain === subdomain) || { subdomain, externalRoutes: [], internalRoutes: [] };
}

// ✅ Helper: clone a response while preserving cookies
function withCookies(baseResponse, newResponse) {
const cookies = baseResponse.cookies.getAll();
cookies.forEach((cookie) => {
newResponse.cookies.set(cookie);
});
return newResponse;
}

export async function proxy(req) {
const activeSession = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
const { pathname, origin } = req.nextUrl;
const url = new URL(req.url);
const hostname = req.headers.get("host") ?? "";
const subdomain = hostname?.split(".")[0];
const port = url.port;

const allowedDomains = [`localhost:${port}`, "thesneakingoutclub.com"];
const isAllowedDomain = allowedDomains.some((domain) => hostname.includes(domain));
const isValidSubdomain = PLATFORM_ROUTES.some((d) => d.subdomain === subdomain);
const isNotSubDomain = !isValidSubdomain;

// create a base response that always sets the cookie
const baseResponse = NextResponse.next();
baseResponse.cookies.set("current_subdomain", isNotSubDomain ? "members" : subdomain, {
path: "/",
httpOnly: false, // readable on client side
secure: process.env.NODE_ENV === "production",
sameSite: "lax"
});
 
if (isAllowedDomain && isNotSubDomain) {
const isInternalRoute = ROOT_INTERNAL_ROUTES.some((r) => pathname.includes(r));
const isExternalRoute = ROOT_EXTERNAL_ROUTES.some((r) => pathname === "/" || pathname.includes(r));

if (!activeSession) {
if (isInternalRoute) return withCookies(baseResponse, NextResponse.redirect(new URL("/login", origin)));
if (isExternalRoute) return baseResponse;
} else {
if (isExternalRoute) return withCookies(baseResponse, NextResponse.redirect(new URL("/dashboard", origin)));
if (isInternalRoute) return baseResponse;
}
}
if (isValidSubdomain) {
const platformRoutes = findPlatformRoutesForSubdomain(subdomain);

const { externalRoutes = [], internalRoutes = [] } = platformRoutes;

const isInternalRoute = internalRoutes.some((r) => pathname.startsWith(`/${r}`));
const isExternalRoute = externalRoutes.some((r) => pathname === "/" || pathname.startsWith(`/${r}`));

// Block invalid routes
const isKnownRoute = isInternalRoute || isExternalRoute;

if (!isKnownRoute) {
return withCookies(
baseResponse,
NextResponse.rewrite(new URL("/not-found", origin))
);
}

//Auth logic
if (!activeSession) {
if (isInternalRoute)
return withCookies(baseResponse, NextResponse.redirect(new URL("/login", origin)));

if (isExternalRoute)
return withCookies(
baseResponse,
NextResponse.rewrite(new URL(`/${subdomain}${url.pathname}`, req.url))
);
}

if (activeSession) {
if (pathname === "/" || isExternalRoute) return withCookies(baseResponse, NextResponse.redirect(new URL("/dashboard", origin)));
if (isInternalRoute) return withCookies(baseResponse, NextResponse.rewrite(new URL(`/${subdomain}${url.pathname}`, req.url)));
}
}

//Default fallback: always return cookie-enabled response
return baseResponse;
}
