import { Inter } from "next/font/google";
import "../../styles/global.css";
import ProvidersLayout from "../../components/layouts/ProvidersLayout";
import InternalLayout from "../../components/layouts/InternalLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	function classNames(...classes) {
		return classes.filter(Boolean).join(" ");
	}

	return (
		<html lang="en" className={classNames(inter.className, "h-full antialiased")} suppressHydrationWarning>
			<body className="min-h-full flex flex-col">
				<ProvidersLayout>
					<InternalLayout>{children}</InternalLayout>
				</ProvidersLayout>
			</body>
		</html>
	);
}
